### ISSUE TITLE
Create Simple Logins

### ISSUE THREAD

**Issue by JackOBrien** [JackOBrien/Concurrent-Editor#6]
Logins should consist of username only at this point

**Comment by JackOBrien** [comment]
Possibly implemented as of [this commit](https://github.com/JackOBrien/Project-Io/commit/b63689d171bab0a7734080fa9fc1dab26589beb3). Untested at this point.

**Comment by maknapp** [comment]
I got logins working, although I don't think would should have user IDs inside the Connector class, as that is only supposed to be networking.

Right now the userId field in the Connector class is only used by the server. We need to pull the userId out and put it in another class that contains the userId and a Connector, and have the server store a list of those objects, rather than just a list of connectors.

Also, the server is assigning userId's by length of the current user list. When we have users disconnecting later on, we are going to get duplicate IDs.

(I also added the rebroadcasting of edits the server receives into this feature-login branch to multiple clients working)
